%% Loading data:
normal692_data = load('reg692_noinj_replog.mat', 'simOut', 'HourOutVals', 'SecOutVals', 'TimeOutVals', 'regWsNames', ...
    'MakeTCentries', 'ExecEntries', 'LookingFwdEntries', 'LookingRevDRPentries', ...
    'LookingRevRNCentries', 'MakeTCgraph', 'ExecGraph', 'LookingFwdGraph', ...
    'LookingRevDRPgraph', 'LookingRevRNCgraph', 'MakeTCblockpath', 'ExecBlockpath', ...
    'LookingFwdBlockpath', 'LookingRevDRPblockpath', 'LookingRevRNCblockpath', 'EventLog');

% operator spoofed:
inj692_data = load('reg692_inj_quarter.mat', 'simOut', 'HourOutVals', 'SecOutVals', 'TimeOutVals', 'regWsNames', ...
    'MakeTCentries', 'ExecEntries', 'LookingFwdEntries', 'LookingRevDRPentries', ...
    'LookingRevRNCentries', 'MakeTCgraph', 'ExecGraph', 'LookingFwdGraph', ...
    'LookingRevDRPgraph', 'LookingRevRNCgraph', 'ExecBlockpath', 'LookingRevDRPblockpath', 'EventLog');
load692_data = load('reg692_load_quarter.mat', 'simOut', 'HourOutVals', 'SecOutVals', 'TimeOutVals', 'regWsNames', ...
    'MakeTCentries', 'ExecEntries', 'LookingFwdEntries', 'LookingRevDRPentries', ...
    'LookingRevRNCentries', 'MakeTCgraph', 'ExecGraph', 'LookingFwdGraph', ...
    'LookingRevDRPgraph', 'LookingRevRNCgraph', 'ExecBlockpath', 'LookingRevDRPblockpath', 'EventLog');

% system spoofed:
inj692spoof_data = load('reg692_spoof_inj.mat', 'simOut', 'HourOutVals', 'SecOutVals', 'TimeOutVals', 'regWsNames', ...
    'MakeTCentries', 'ExecEntries', 'LookingFwdEntries', 'LookingRevDRPentries', ...
    'LookingRevRNCentries', 'MakeTCgraph', 'ExecGraph', 'LookingFwdGraph', ...
    'LookingRevDRPgraph', 'LookingRevRNCgraph', 'ExecBlockpath', 'LookingRevDRPblockpath', 'EventLog');
load692spoof_data = load('reg692_spoof_load.mat', 'simOut', 'HourOutVals', 'SecOutVals', 'TimeOutVals', 'regWsNames', ...
    'MakeTCentries', 'ExecEntries', 'LookingFwdEntries', 'LookingRevDRPentries', ...
    'LookingRevRNCentries', 'MakeTCgraph', 'ExecGraph', 'LookingFwdGraph', ...
    'LookingRevDRPgraph', 'LookingRevRNCgraph', 'ExecBlockpath', 'LookingRevDRPblockpath', 'EventLog');

fieldnames = {'MakeTC' 'Exec' 'LFwd' 'LRev' 'RevN'};
N = 96;
Time = normal692_data.TimeOutVals/3600;
regWsNames = normal692_data.regWsNames;

%% making digraphs probabilistic (didn't do in simulation script):
[normal692_data.MakeTCgraph, normal692_data.ExecGraph, normal692_data.LookingFwdGraph, ...
    normal692_data.LookingRevDRPgraph, normal692_data.LookingRevRNCgraph] = ...
        BatchMakeProbabilistic(regWsNames, normal692_data.MakeTCgraph, normal692_data.ExecGraph, ...
        normal692_data.LookingFwdGraph, normal692_data.LookingRevDRPgraph, normal692_data.LookingRevRNCgraph);
    
[inj692_data.MakeTCgraph, inj692_data.ExecGraph, inj692_data.LookingFwdGraph, ...
    inj692_data.LookingRevDRPgraph, inj692_data.LookingRevRNCgraph] = ...
        BatchMakeProbabilistic(regWsNames, inj692_data.MakeTCgraph, inj692_data.ExecGraph, ...
        inj692_data.LookingFwdGraph, inj692_data.LookingRevDRPgraph, inj692_data.LookingRevRNCgraph);
    
[load692_data.MakeTCgraph, load692_data.ExecGraph, load692_data.LookingFwdGraph, ...
    load692_data.LookingRevDRPgraph, load692_data.LookingRevRNCgraph] = ...
        BatchMakeProbabilistic(regWsNames, load692_data.MakeTCgraph, load692_data.ExecGraph, ...
        load692_data.LookingFwdGraph, load692_data.LookingRevDRPgraph, load692_data.LookingRevRNCgraph);
    
[inj692spoof_data.MakeTCgraph, inj692spoof_data.ExecGraph, inj692spoof_data.LookingFwdGraph, ...
    inj692spoof_data.LookingRevDRPgraph, inj692spoof_data.LookingRevRNCgraph] = ...
        BatchMakeProbabilistic(regWsNames, inj692spoof_data.MakeTCgraph, inj692spoof_data.ExecGraph, ...
        inj692spoof_data.LookingFwdGraph, inj692spoof_data.LookingRevDRPgraph, inj692spoof_data.LookingRevRNCgraph);
    
[load692spoof_data.MakeTCgraph, load692spoof_data.ExecGraph, load692spoof_data.LookingFwdGraph, ...
    load692spoof_data.LookingRevDRPgraph, load692spoof_data.LookingRevRNCgraph] = ...
        BatchMakeProbabilistic(regWsNames, load692spoof_data.MakeTCgraph, load692spoof_data.ExecGraph, ...
        load692spoof_data.LookingFwdGraph, load692spoof_data.LookingRevDRPgraph, load692spoof_data.LookingRevRNCgraph);

%% comparing MakeTC and Exec sequences for normal load pattern:

% shows 100% correlation between MakeTapChange and Execution state
% transitions (not anomalous)
for phase = 1:3
    figure(phase);
    subplot(1,2,1);
    PlotNormalized(getfield(normal692_data.MakeTCgraph, regWsNames{phase}), normal692_data.MakeTCblockpath, ...
        normal692_data.MakeTCentries(phase), N, '', '.Finished');
    
    subplot(1,2,2);
    PlotNormalized(getfield(normal692_data.ExecGraph, regWsNames{phase}), normal692_data.ExecBlockpath, ...
        normal692_data.ExecEntries(phase), N, '.ParseAction', '.Finished');
end
    
    
%%

for phase = 1:3
    figure(4);
    subplot(1,3,phase);
    PlotNormalized(getfield(MakeTCgraph, regWsNames{phase}), MakeTCblockpath, ...
        MakeTCentries(phase), N, '', '.Finished');

    figure(5);
    subplot(1,3,phase);
    PlotNormalized(getfield(ExecGraph, regWsNames{phase}), ExecBlockpath, ...
        ExecEntries(phase), N, '.ParseAction', '.Finished');
    
    figure(6);
    subplot(1,3,phase);
    PlotNormalized(getfield(LookingFwdGraph, regWsNames{phase}), ...
        LookingFwdBlockpath, LookingFwdEntries(phase), N, '', '.Finished');
    
    figure(7);
    subplot(1,3,phase);
    PlotNormalized(getfield(LookingRevDRPgraph, regWsNames{phase}), ...
        LookingRevDRPblockpath, LookingRevDRPentries(phase), N, '', '.Finished');
    
    figure(8);
    subplot(1,3,phase);
    PlotNormalized(getfield(LookingRevRNCgraph, regWsNames{phase}), ...
        LookingRevRNCblockpath, LookingRevRNCentries(phase), N, '', '.Finished');
end