%% Load data:
inj_data = load('reg692_inj.mat', 'simOut', 'HourOutVals', 'SecOutVals', 'regWsNames', ...
    'MakeTCentries', 'ExecEntries', 'LookingFwdEntries', 'LookingRevDRPentries', ...
    'LookingRevRNCentries', 'MakeTCgraph', 'ExecGraph', 'LookingFwdGraph', ...
    'LookingRevDRPgraph', 'LookingRevRNCgraph', 'ExecBlockpath', 'EventLog');
noinj_data = load('reg692_noinj.mat', 'simOut', 'HourOutVals', 'SecOutVals', 'regWsNames', ...
    'MakeTCentries', 'ExecEntries', 'LookingFwdEntries', 'LookingRevDRPentries', ...
    'LookingRevRNCentries', 'MakeTCgraph', 'ExecGraph', 'LookingFwdGraph', ...
    'LookingRevDRPgraph', 'LookingRevRNCgraph', 'ExecBlockpath', 'EventLog');

%% view probabilities of the sequences that executed at each timestep:

probability_inj = MakeProbChart(inj_data.simOut, inj_data.HourOutVals, inj_data.SecOutVals, 1:3, ...
    {'MakeTC' 'Exec' 'LFwd' 'LRev' 'RevN'}, ...
    [inj_data.MakeTCentries inj_data.ExecEntries inj_data.LookingFwdEntries inj_data.LookingRevDRPentries inj_data.LookingRevRNCentries], ...
    inj_data.MakeTCgraph, inj_data.ExecGraph, inj_data.LookingFwdGraph, inj_data.LookingRevDRPgraph, inj_data.LookingRevRNCgraph);
struct2table(probability_inj)

probability_noinj = MakeProbChart(noinj_data.simOut, noinj_data.HourOutVals, noinj_data.SecOutVals, 1:3, ...
    {'MakeTC' 'Exec' 'LFwd' 'LRev' 'RevN'}, ...
    [noinj_data.MakeTCentries noinj_data.ExecEntries noinj_data.LookingFwdEntries noinj_data.LookingRevDRPentries noinj_data.LookingRevRNCentries], ...
    noinj_data.MakeTCgraph, noinj_data.ExecGraph, noinj_data.LookingFwdGraph, noinj_data.LookingRevDRPgraph, noinj_data.LookingRevRNCgraph);
struct2table(probability_noinj)

%% view probabilities of one sequence based on another sequence's Markov chain:

ni_thru_i = MakeProbChart(noinj_data.simOut, inj_data.HourOutVals, inj_data.SecOutVals, 1:3, ...
    {'MakeTC' 'Exec' 'LFwd' 'LRev' 'RevN'}, ...
    [inj_data.MakeTCentries inj_data.ExecEntries inj_data.LookingFwdEntries inj_data.LookingRevDRPentries inj_data.LookingRevRNCentries], ...
    inj_data.MakeTCgraph, inj_data.ExecGraph, inj_data.LookingFwdGraph, inj_data.LookingRevDRPgraph, inj_data.LookingRevRNCgraph);
struct2table(ni_thru_i)

i_thru_ni = MakeProbChart(inj_data.simOut, noinj_data.HourOutVals, noinj_data.SecOutVals, 1:3, ...
    {'MakeTC' 'Exec' 'LFwd' 'LRev' 'RevN'}, ...
    [noinj_data.MakeTCentries noinj_data.ExecEntries noinj_data.LookingFwdEntries noinj_data.LookingRevDRPentries noinj_data.LookingRevRNCentries], ...
    noinj_data.MakeTCgraph, noinj_data.ExecGraph, noinj_data.LookingFwdGraph, noinj_data.LookingRevDRPgraph, noinj_data.LookingRevRNCgraph);
struct2table(i_thru_ni)

%% side-by-side comparison with single phase and single chart:

i_thru_ni_sing = MakeProbChart(inj_data.simOut, noinj_data.HourOutVals, ...
    noinj_data.SecOutVals, 3, ...
    {'Exec'}, noinj_data.ExecEntries, noinj_data.ExecGraph);
i_thru_ni_tab = struct2table(i_thru_ni_sing)

i_thru_i_sing = MakeProbChart(inj_data.simOut, noinj_data.HourOutVals, ...
    noinj_data.SecOutVals, 3, ...
    {'Exec'}, inj_data.ExecEntries, inj_data.ExecGraph);
i_thru_i_tab = struct2table(i_thru_i_sing)

%% Plot sequence:
loclog = find(inj_data.simOut(1).logsout, '-regexp', 'BlockPath', ...
                    sprintf('\\w*%s\\w*', inj_data.regWsNames{phase}));
                
phase = 2;
                
h = PlotSequence(MakeDigraphProb( getfield(inj_data.ExecGraph, inj_data.regWsNames{phase}) ), ...
    inj_data.ExecBlockpath, inj_data.ExecEntries(phase), length(inj_data.simOut), ...
        '.ParseAction', '.Finished', loclog);

%% Counting occurrences:






