%% Loading data:
normal692_data = load('reg692_noinj_replog.mat', 'simOut', 'HourOutVals', 'SecOutVals', 'TimeOutVals', 'regWsNames', ...
    'MakeTCentries', 'ExecEntries', 'LookingFwdEntries', 'LookingRevDRPentries', ...
    'LookingRevRNCentries', 'MakeTCgraph', 'ExecGraph', 'LookingFwdGraph', ...
    'LookingRevDRPgraph', 'LookingRevRNCgraph', 'ExecBlockpath', 'LookingRevDRPblockpath', 'EventLog');
normal650_data = load('reg650_noinj_replog.mat', 'simOut', 'HourOutVals', 'SecOutVals', 'TimeOutVals', 'regWsNames', ...
    'MakeTCentries', 'ExecEntries', 'LookingFwdEntries', 'LookingRevDRPentries', ...
    'LookingRevRNCentries', 'MakeTCgraph', 'ExecGraph', 'LookingFwdGraph', ...
    'LookingRevDRPgraph', 'LookingRevRNCgraph', 'ExecBlockpath', 'LookingRevDRPblockpath', 'EventLog');

% operator spoofed:
inj692_data = load('reg692_inj_quarter.mat', 'simOut', 'HourOutVals', 'SecOutVals', 'TimeOutVals', 'regWsNames', ...
    'MakeTCentries', 'ExecEntries', 'LookingFwdEntries', 'LookingRevDRPentries', ...
    'LookingRevRNCentries', 'MakeTCgraph', 'ExecGraph', 'LookingFwdGraph', ...
    'LookingRevDRPgraph', 'LookingRevRNCgraph', 'ExecBlockpath', 'LookingRevDRPblockpath', 'EventLog');
load692_data = load('reg692_load_quarter.mat', 'simOut', 'HourOutVals', 'SecOutVals', 'TimeOutVals', 'regWsNames', ...
    'MakeTCentries', 'ExecEntries', 'LookingFwdEntries', 'LookingRevDRPentries', ...
    'LookingRevRNCentries', 'MakeTCgraph', 'ExecGraph', 'LookingFwdGraph', ...
    'LookingRevDRPgraph', 'LookingRevRNCgraph', 'ExecBlockpath', 'LookingRevDRPblockpath', 'EventLog');
inj650_data = load('reg650_inj_quarter.mat', 'simOut', 'HourOutVals', 'SecOutVals', 'TimeOutVals', 'regWsNames', ...
    'MakeTCentries', 'ExecEntries', 'LookingFwdEntries', 'LookingRevDRPentries', ...
    'LookingRevRNCentries', 'MakeTCgraph', 'ExecGraph', 'LookingFwdGraph', ...
    'LookingRevDRPgraph', 'LookingRevRNCgraph', 'ExecBlockpath', 'LookingRevDRPblockpath', 'EventLog');
load650_data = load('reg650_load_quarter.mat', 'simOut', 'HourOutVals', 'SecOutVals', 'TimeOutVals', 'regWsNames', ...
    'MakeTCentries', 'ExecEntries', 'LookingFwdEntries', 'LookingRevDRPentries', ...
    'LookingRevRNCentries', 'MakeTCgraph', 'ExecGraph', 'LookingFwdGraph', ...
    'LookingRevDRPgraph', 'LookingRevRNCgraph', 'ExecBlockpath', 'LookingRevDRPblockpath', 'EventLog');


% system spoofed:
inj692spoof_data = load('reg692_spoof_inj.mat', 'simOut', 'HourOutVals', 'SecOutVals', 'TimeOutVals', 'regWsNames', ...
    'MakeTCentries', 'ExecEntries', 'LookingFwdEntries', 'LookingRevDRPentries', ...
    'LookingRevRNCentries', 'MakeTCgraph', 'ExecGraph', 'LookingFwdGraph', ...
    'LookingRevDRPgraph', 'LookingRevRNCgraph', 'ExecBlockpath', 'LookingRevDRPblockpath', 'EventLog');
load692spoof_data = load('reg692_spoof_load.mat', 'simOut', 'HourOutVals', 'SecOutVals', 'TimeOutVals', 'regWsNames', ...
    'MakeTCentries', 'ExecEntries', 'LookingFwdEntries', 'LookingRevDRPentries', ...
    'LookingRevRNCentries', 'MakeTCgraph', 'ExecGraph', 'LookingFwdGraph', ...
    'LookingRevDRPgraph', 'LookingRevRNCgraph', 'ExecBlockpath', 'LookingRevDRPblockpath', 'EventLog');
inj650spoof_data = load('reg650_spoof_inj.mat', 'simOut', 'HourOutVals', 'SecOutVals', 'TimeOutVals', 'regWsNames', ...
    'MakeTCentries', 'ExecEntries', 'LookingFwdEntries', 'LookingRevDRPentries', ...
    'LookingRevRNCentries', 'MakeTCgraph', 'ExecGraph', 'LookingFwdGraph', ...
    'LookingRevDRPgraph', 'LookingRevRNCgraph', 'ExecBlockpath', 'LookingRevDRPblockpath', 'EventLog');
load650spoof_data = load('reg650_spoof_load.mat', 'simOut', 'HourOutVals', 'SecOutVals', 'TimeOutVals', 'regWsNames', ...
    'MakeTCentries', 'ExecEntries', 'LookingFwdEntries', 'LookingRevDRPentries', ...
    'LookingRevRNCentries', 'MakeTCgraph', 'ExecGraph', 'LookingFwdGraph', ...
    'LookingRevDRPgraph', 'LookingRevRNCgraph', 'ExecBlockpath', 'LookingRevDRPblockpath', 'EventLog');


fieldnames = {'MakeTC' 'Exec' 'LFwd' 'LRev' 'RevN'};
N = 96;
Time = normal692_data.TimeOutVals/3600;
regWsNames = normal692_data.regWsNames;

%% making digraphs probabilistic (didn't do in simulation script):
[normal692_data.MakeTCgraph, normal692_data.ExecGraph, normal692_data.LookingFwdGraph, ...
    normal692_data.LookingRevDRPgraph, normal692_data.LookingRevRNCgraph] = ...
        BatchMakeProbabilistic(regWsNames, normal692_data.MakeTCgraph, normal692_data.ExecGraph, ...
        normal692_data.LookingFwdGraph, normal692_data.LookingRevDRPgraph, normal692_data.LookingRevRNCgraph);
    
[inj692_data.MakeTCgraph, inj692_data.ExecGraph, inj692_data.LookingFwdGraph, ...
    inj692_data.LookingRevDRPgraph, inj692_data.LookingRevRNCgraph] = ...
        BatchMakeProbabilistic(regWsNames, inj692_data.MakeTCgraph, inj692_data.ExecGraph, ...
        inj692_data.LookingFwdGraph, inj692_data.LookingRevDRPgraph, inj692_data.LookingRevRNCgraph);
    
[load692_data.MakeTCgraph, load692_data.ExecGraph, load692_data.LookingFwdGraph, ...
    load692_data.LookingRevDRPgraph, load692_data.LookingRevRNCgraph] = ...
        BatchMakeProbabilistic(regWsNames, load692_data.MakeTCgraph, load692_data.ExecGraph, ...
        load692_data.LookingFwdGraph, load692_data.LookingRevDRPgraph, load692_data.LookingRevRNCgraph);
    
[inj692spoof_data.MakeTCgraph, inj692spoof_data.ExecGraph, inj692spoof_data.LookingFwdGraph, ...
    inj692spoof_data.LookingRevDRPgraph, inj692spoof_data.LookingRevRNCgraph] = ...
        BatchMakeProbabilistic(regWsNames, inj692spoof_data.MakeTCgraph, inj692spoof_data.ExecGraph, ...
        inj692spoof_data.LookingFwdGraph, inj692spoof_data.LookingRevDRPgraph, inj692spoof_data.LookingRevRNCgraph);
    
[load692spoof_data.MakeTCgraph, load692spoof_data.ExecGraph, load692spoof_data.LookingFwdGraph, ...
    load692spoof_data.LookingRevDRPgraph, load692spoof_data.LookingRevRNCgraph] = ...
        BatchMakeProbabilistic(regWsNames, load692spoof_data.MakeTCgraph, load692spoof_data.ExecGraph, ...
        load692spoof_data.LookingFwdGraph, load692spoof_data.LookingRevDRPgraph, load692spoof_data.LookingRevRNCgraph);

%% bus 692 operator spoof: probabilities of sequences692 based on normal operating conditions Markov chain:

% reference - normal conditions:
[normal_thru_normal, sequences692] = MakeProbChart(normal692_data.simOut, normal692_data.HourOutVals, normal692_data.SecOutVals, 1:3, ...
    fieldnames, ...
    [normal692_data.MakeTCentries normal692_data.ExecEntries normal692_data.LookingFwdEntries normal692_data.LookingRevDRPentries normal692_data.LookingRevRNCentries], ...
    normal692_data.MakeTCgraph, normal692_data.ExecGraph, normal692_data.LookingFwdGraph, normal692_data.LookingRevDRPgraph, normal692_data.LookingRevRNCgraph, 'ShowBudget');

% unexpected injection:
inj692_thru_normal = MakeProbChart(inj692_data.simOut, normal692_data.HourOutVals, normal692_data.SecOutVals, 1:3, ...
    fieldnames, ...
    [normal692_data.MakeTCentries normal692_data.ExecEntries normal692_data.LookingFwdEntries normal692_data.LookingRevDRPentries normal692_data.LookingRevRNCentries], ...
    normal692_data.MakeTCgraph, normal692_data.ExecGraph, normal692_data.LookingFwdGraph, normal692_data.LookingRevDRPgraph, normal692_data.LookingRevRNCgraph, ...
    'ShowBudget', sequences692);

% unexpected load:
load692_thru_normal = MakeProbChart(load692_data.simOut, normal692_data.HourOutVals, normal692_data.SecOutVals, 1:3, ...
    fieldnames, ...
    [normal692_data.MakeTCentries normal692_data.ExecEntries normal692_data.LookingFwdEntries normal692_data.LookingRevDRPentries normal692_data.LookingRevRNCentries], ...
    normal692_data.MakeTCgraph, normal692_data.ExecGraph, normal692_data.LookingFwdGraph, normal692_data.LookingRevDRPgraph, normal692_data.LookingRevRNCgraph, ...
    'ShowBudget', sequences692);

%% bus 692 - reference: normal through normal

matching_normal = compareCharts(normal_thru_normal, normal_thru_normal, fieldnames, ...
    regWsNames, sequences692, N);

[matching3D_normal, matching_tab_normal] = compareChartsOverTime( normal_thru_normal, normal_thru_normal, fieldnames, ...
    regWsNames, sequences692, N, 'Window', (2*N/24) ); %2 hr window

figure(1)
plotMatchingCoeff('Normal', 'RegControl1', Time, matching_tab_normal, normal_thru_normal);
figure(2)
plotMatchingCoeff('Normal', 'RegControl2', Time, matching_tab_normal, normal_thru_normal);
figure(3)
plotMatchingCoeff('Normal', 'RegControl3', Time, matching_tab_normal, normal_thru_normal);

%% bus 692 - operator spoof - injection - probabilities over time:

matching_692inj = compareCharts(normal_thru_normal, inj692_thru_normal, fieldnames, ...
    regWsNames, sequences692, N);

[matching3D_692inj, matching_tab_692inj] = compareChartsOverTime( normal_thru_normal, inj692_thru_normal, fieldnames, ...
    regWsNames, sequences692, N, 'Window', (2*N/24) );

figure(1)
plotMatchingCoeff('Operator Spoof: Injection', 'RegControl1', Time, matching_tab_692inj, inj692_thru_normal);
figure(2)
plotMatchingCoeff('Operator Spoof: Injection', 'RegControl2', Time, matching_tab_692inj, inj692_thru_normal);
figure(3)
plotMatchingCoeff('Operator Spoof: Injection', 'RegControl3', Time, matching_tab_692inj, inj692_thru_normal);

%% bus 692 - operator spoof - load connected - probabilities over time:

matching_692load = compareCharts(normal_thru_normal, load692_thru_normal, fieldnames, ...
    regWsNames, sequences692, N);

[matching3D_692load, matching_tab_692load] = compareChartsOverTime( normal_thru_normal, load692_thru_normal, fieldnames, ...
    regWsNames, sequences692, N, 'Window', (2*N/24) );

figure(1)
plotMatchingCoeff('Operator Spoof: Load Connected', 'RegControl1', Time, matching_tab_692load, load692_thru_normal);
figure(2)
plotMatchingCoeff('Operator Spoof: Load Connected', 'RegControl2', Time, matching_tab_692load, load692_thru_normal);
figure(3)
plotMatchingCoeff('Operator Spoof: Load Connected', 'RegControl3', Time, matching_tab_692load, load692_thru_normal);

%% bus 692 - system spoof: probabilities of sequences692 based on normal operating conditions Markov chain:

% reference - normal conditions:
% [normal_thru_normal, sequences692] = MakeProbChart(normal692_data.simOut, normal692_data.HourOutVals, normal692_data.SecOutVals, 1:3, ...
%     fieldnames, ...
%     [normal692_data.MakeTCentries normal692_data.ExecEntries normal692_data.LookingFwdEntries normal692_data.LookingRevDRPentries normal692_data.LookingRevRNCentries], ...
%     normal692_data.MakeTCgraph, normal692_data.ExecGraph, normal692_data.LookingFwdGraph, normal692_data.LookingRevDRPgraph, normal692_data.LookingRevRNCgraph, 'ShowBudget');

% unexpected injection:
inj692spoof_thru_normal = MakeProbChart(inj692spoof_data.simOut, normal692_data.HourOutVals, normal692_data.SecOutVals, 1:3, ...
    fieldnames, ...
    [normal692_data.MakeTCentries normal692_data.ExecEntries normal692_data.LookingFwdEntries normal692_data.LookingRevDRPentries normal692_data.LookingRevRNCentries], ...
    normal692_data.MakeTCgraph, normal692_data.ExecGraph, normal692_data.LookingFwdGraph, normal692_data.LookingRevDRPgraph, normal692_data.LookingRevRNCgraph, ...
    'ShowBudget', sequences692);

% unexpected load:
load692spoof_thru_normal = MakeProbChart(load692spoof_data.simOut, normal692_data.HourOutVals, normal692_data.SecOutVals, 1:3, ...
    fieldnames, ...
    [normal692_data.MakeTCentries normal692_data.ExecEntries normal692_data.LookingFwdEntries normal692_data.LookingRevDRPentries normal692_data.LookingRevRNCentries], ...
    normal692_data.MakeTCgraph, normal692_data.ExecGraph, normal692_data.LookingFwdGraph, normal692_data.LookingRevDRPgraph, normal692_data.LookingRevRNCgraph, ...
    'ShowBudget', sequences692);

%% bus 692 - system spoof - injection - probabilities over time:

matching_inj692spoof = compareCharts(normal_thru_normal, inj692spoof_thru_normal, fieldnames, ...
    regWsNames, sequences692, N);

[matching3D_inj692spoof, matching_tab_inj692spoof] = compareChartsOverTime( normal_thru_normal, inj692spoof_thru_normal, fieldnames, ...
    regWsNames, sequences692, N, 'Window', (2*N/24) );

% gives 100% match

figure(1)
plotMatchingCoeff('System Spoof: Injection', 'RegControl1', Time, matching_tab_inj692spoof, inj692spoof_thru_normal);
figure(2)
plotMatchingCoeff('System Spoof: Injection', 'RegControl2', Time, matching_tab_inj692spoof, inj692spoof_thru_normal);
figure(3)
plotMatchingCoeff('System Spoof: Injection', 'RegControl3', Time, matching_tab_inj692spoof, inj692spoof_thru_normal);

%% bus 692 - system spoof - load connected - probabilities over time:

matching_load692spoof = compareCharts(normal_thru_normal, load692spoof_thru_normal, fieldnames, ...
    regWsNames, sequences692, N);

[matching3D_load692spoof, matching_tab_load692spoof] = compareChartsOverTime( normal_thru_normal, load692spoof_thru_normal, fieldnames, ...
    regWsNames, sequences692, N, 'Window', (2*N/24) );

% gives 100% match

figure(1)
plotMatchingCoeff('System Spoof: Load Connected', 'RegControl1', Time, matching_tab_load692spoof, load692spoof_thru_normal);
figure(2)
plotMatchingCoeff('System Spoof: Load Connected', 'RegControl2', Time, matching_tab_load692spoof, load692spoof_thru_normal);
figure(3)
plotMatchingCoeff('System Spoof: Load Connected', 'RegControl3', Time, matching_tab_load692spoof, load692spoof_thru_normal);

%% bus 650 operator spoof: probabilities of sequences692 based on normal operating conditions Markov chain:

% reference - normal conditions:
[normal_thru_normal650, sequences650] = MakeProbChart(normal650_data.simOut, normal650_data.HourOutVals, normal650_data.SecOutVals, 1:3, ...
    fieldnames, ...
    [normal650_data.MakeTCentries normal650_data.ExecEntries normal650_data.LookingFwdEntries normal650_data.LookingRevDRPentries normal650_data.LookingRevRNCentries], ...
    normal650_data.MakeTCgraph, normal650_data.ExecGraph, normal650_data.LookingFwdGraph, normal650_data.LookingRevDRPgraph, normal650_data.LookingRevRNCgraph, 'ShowBudget');

% unexpected injection:
inj650_thru_normal = MakeProbChart(inj650_data.simOut, normal650_data.HourOutVals, normal650_data.SecOutVals, 1:3, ...
    fieldnames, ...
    [normal650_data.MakeTCentries normal650_data.ExecEntries normal650_data.LookingFwdEntries normal650_data.LookingRevDRPentries normal650_data.LookingRevRNCentries], ...
    normal650_data.MakeTCgraph, normal650_data.ExecGraph, normal650_data.LookingFwdGraph, normal650_data.LookingRevDRPgraph, normal650_data.LookingRevRNCgraph, ...
    'ShowBudget', sequences650);

% unexpected load
load650_thru_normal = MakeProbChart(load650_data.simOut, normal692_data.HourOutVals, normal692_data.SecOutVals, 1:3, ...
    fieldnames, ...
    [normal692_data.MakeTCentries normal692_data.ExecEntries normal692_data.LookingFwdEntries normal692_data.LookingRevDRPentries normal692_data.LookingRevRNCentries], ...
    normal692_data.MakeTCgraph, normal692_data.ExecGraph, normal692_data.LookingFwdGraph, normal692_data.LookingRevDRPgraph, normal692_data.LookingRevRNCgraph, ...
    'ShowBudget', sequences650);

%% bus 650 - reference: normal through normal

matching_normal650 = compareCharts(normal_thru_normal650, normal_thru_normal650, fieldnames, ...
    regWsNames, sequences650, N);

[matching3D_normal650, matching_tab_normal650] = compareChartsOverTime( normal_thru_normal650, normal_thru_normal650, fieldnames, ...
    regWsNames, sequences650, N, 'Window', (2*N/24) ); %2 hr window, 8 data points (3h --> 12dp)

figure(1)
plotMatchingCoeff('Normal', 'RegControl1', Time, matching_tab_normal650, normal_thru_normal650);
figure(2)
plotMatchingCoeff('Normal', 'RegControl2', Time, matching_tab_normal650, normal_thru_normal650);
figure(3)
plotMatchingCoeff('Normal', 'RegControl3', Time, matching_tab_normal650, normal_thru_normal650);

%% bus 650 - operator spoof - injection - probabilities over time:

matching_650inj = compareCharts(normal_thru_normal650, inj650_thru_normal, fieldnames, ...
    regWsNames, sequences650, N);

[matching3D_650inj, matching_tab_650inj] = compareChartsOverTime( normal_thru_normal650, inj650_thru_normal, fieldnames, ...
    regWsNames, sequences650, N, 'Window', (3*N/24) );

figure(2)
subplot(3,1,1)
plotMatchingCoeff('Operator Spoof: Injection', 'RegControl1', Time, matching_tab_650inj, inj650_thru_normal);
subplot(3,1,2)
plotMatchingCoeff('Operator Spoof: Injection', 'RegControl2', Time, matching_tab_650inj, inj650_thru_normal);
subplot(3,1,3)
plotMatchingCoeff('Operator Spoof: Injection', 'RegControl3', Time, matching_tab_650inj, inj650_thru_normal);

%% bus 650 - operator spoof - load connected - probabilities over time:

matching_650load = compareCharts(normal_thru_normal650, load650_thru_normal, fieldnames, ...
    regWsNames, sequences650, N);

[matching3D_650load, matching_tab_650load] = compareChartsOverTime( normal_thru_normal650, load650_thru_normal, fieldnames, ...
    regWsNames, sequences650, N, 'Window', (2*N/24) );

figure(1)
plotMatchingCoeff('Operator Spoof: Load Connected', 'RegControl1', Time, matching_tab_650load, load650_thru_normal);
figure(2)
plotMatchingCoeff('Operator Spoof: Load Connected', 'RegControl2', Time, matching_tab_650load, load650_thru_normal);
figure(3)
plotMatchingCoeff('Operator Spoof: Load Connected', 'RegControl3', Time, matching_tab_650load, load650_thru_normal);

%% bus 650 - system spoof: probabilities of sequences692 based on normal operating conditions Markov chain:

% reference - normal conditions:
% [normal_thru_normal, sequences692] = MakeProbChart(normal692_data.simOut, normal692_data.HourOutVals, normal692_data.SecOutVals, 1:3, ...
%     fieldnames, ...
%     [normal692_data.MakeTCentries normal692_data.ExecEntries normal692_data.LookingFwdEntries normal692_data.LookingRevDRPentries normal692_data.LookingRevRNCentries], ...
%     normal692_data.MakeTCgraph, normal692_data.ExecGraph, normal692_data.LookingFwdGraph, normal692_data.LookingRevDRPgraph, normal692_data.LookingRevRNCgraph, 'ShowBudget');

% unexpected injection:
inj650spoof_thru_normal = MakeProbChart(inj650spoof_data.simOut, normal650_data.HourOutVals, normal650_data.SecOutVals, 1:3, ...
    fieldnames, ...
    [normal650_data.MakeTCentries normal650_data.ExecEntries normal650_data.LookingFwdEntries normal650_data.LookingRevDRPentries normal650_data.LookingRevRNCentries], ...
    normal650_data.MakeTCgraph, normal650_data.ExecGraph, normal650_data.LookingFwdGraph, normal650_data.LookingRevDRPgraph, normal650_data.LookingRevRNCgraph, ...
    'ShowBudget', sequences650);

% unexpected load:
load650spoof_thru_normal = MakeProbChart(load650spoof_data.simOut, normal650_data.HourOutVals, normal650_data.SecOutVals, 1:3, ...
    fieldnames, ...
    [normal650_data.MakeTCentries normal650_data.ExecEntries normal650_data.LookingFwdEntries normal650_data.LookingRevDRPentries normal650_data.LookingRevRNCentries], ...
    normal650_data.MakeTCgraph, normal650_data.ExecGraph, normal650_data.LookingFwdGraph, normal650_data.LookingRevDRPgraph, normal650_data.LookingRevRNCgraph, ...
    'ShowBudget', sequences650);

%% bus 650 - system spoof - injection - probabilities over time:

matching_inj650spoof = compareCharts(normal_thru_normal650, inj650spoof_thru_normal, fieldnames, ...
    regWsNames, sequences650, N);

[matching3D_inj650spoof, matching_tab_inj650spoof] = compareChartsOverTime( normal_thru_normal650, inj650spoof_thru_normal, fieldnames, ...
    regWsNames, sequences650, N, 'Window', (2*N/24) );

% gives 100% match

figure(1)
plotMatchingCoeff('System Spoof: Injection', 'RegControl1', Time, matching_tab_inj650spoof, inj650spoof_thru_normal);
figure(2)
plotMatchingCoeff('System Spoof: Injection', 'RegControl2', Time, matching_tab_inj650spoof, inj650spoof_thru_normal);
figure(3)
plotMatchingCoeff('System Spoof: Injection', 'RegControl3', Time, matching_tab_inj650spoof, inj650spoof_thru_normal);

%% bus 650 - system spoof - load connected - probabilities over time:

matching_load650spoof = compareCharts(normal_thru_normal, load650spoof_thru_normal, fieldnames, ...
    regWsNames, sequences650, N);

[matching3D_load650spoof, matching_tab_load650spoof] = compareChartsOverTime( normal_thru_normal, load650spoof_thru_normal, fieldnames, ...
    regWsNames, sequences650, N, 'Window', (2*N/24) );

% gives 100% match

figure(1)
plotMatchingCoeff('System Spoof: Load Connected', 'RegControl1', Time, matching_tab_load650spoof, load650spoof_thru_normal);
figure(2)
plotMatchingCoeff('System Spoof: Load Connected', 'RegControl2', Time, matching_tab_load650spoof, load650spoof_thru_normal);
figure(3)
plotMatchingCoeff('System Spoof: Load Connected', 'RegControl3', Time, matching_tab_load650spoof, load650spoof_thru_normal);

%% All state machines of a single phase:

rc1_sm = horzcat(i_thru_ni_tab(:, {'idx' 'hr' 'sec'}), i_thru_ni_tab.RegControl1)
rc2_sm = horzcat(i_thru_ni_tab(:, {'idx' 'hr' 'sec'}), i_thru_ni_tab.RegControl2)
rc3_sm = horzcat(i_thru_ni_tab(:, {'idx' 'hr' 'sec'}), i_thru_ni_tab.RegControl3)


%% Same state machine across all phases:

i_thru_ni_sm_order = inner2outer(i_thru_ni_tab);

all_MakeTC = horzcat(i_thru_ni_sm_order(:, {'idx' 'hr' 'sec'}), i_thru_ni_sm_order.MakeTC)
all_Exec = horzcat(i_thru_ni_sm_order(:, {'idx' 'hr' 'sec'}), i_thru_ni_sm_order.Exec)
all_LFwd = horzcat(i_thru_ni_sm_order(:, {'idx' 'hr' 'sec'}), i_thru_ni_sm_order.LFwd)
all_LRev = horzcat(i_thru_ni_sm_order(:, {'idx' 'hr' 'sec'}), i_thru_ni_sm_order.LRev)
all_RevN = horzcat(i_thru_ni_sm_order(:, {'idx' 'hr' 'sec'}), i_thru_ni_sm_order.LRev)

%% Investigating RegControl1 LRev:

phase = 1;

% at nn = 2 (what should happen all the time):
loclog = find(normal692_data.simOut(2).logsout, '-regexp', 'BlockPath', ...
                    sprintf('\\w*%s\\w*', normal692_data.regWsNames{phase}));
                
[po_seq, uniqueSeq, ID, count] = ...
    ProbOfSequence( getfield(noinj_data.LookingRevDRPgraph, noinj_data.regWsNames{phase}), ...
   noinj_data.LookingRevDRPentries(phase)/96, loclog, struct.empty);

uniqueSeq.Sequence

figure(1)                
h = PlotSequence(MakeDigraphProb( getfield(noinj_data.LookingRevDRPgraph, noinj_data.regWsNames{phase}) ), ...
    noinj_data.LookingRevDRPblockpath, noinj_data.LookingRevDRPentries(phase), length(normal692_data.simOut), ...
        '', '.Finished', loclog);

% at nn = 3 (what happens from nn=3:96 that shouldn't occur at all):
loclog = find(normal692_data.simOut(3).logsout, '-regexp', 'BlockPath', ...
                    sprintf('\\w*%s\\w*', normal692_data.regWsNames{phase}));
                
[po_seq, uniqueSeq, ID, count] = ...
    ProbOfSequence( getfield(noinj_data.LookingRevDRPgraph, noinj_data.regWsNames{phase}), ...
   noinj_data.LookingRevDRPentries(phase)/96, loclog, struct.empty);

uniqueSeq.Sequence

figure(2)                
h = PlotSequence(MakeDigraphProb( getfield(noinj_data.LookingRevDRPgraph, noinj_data.regWsNames{phase}) ), ...
    noinj_data.LookingRevDRPblockpath, noinj_data.LookingRevDRPentries(phase), length(normal692_data.simOut), ...
        '', '.Finished', loclog);







